# Generated by Django 4.1 on 2022-09-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprojectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartament',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apartament',
            name='matricula_inmueble',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='apartament',
            name='tiene_piscina',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=('NO', 'NO'), max_length=2),
        ),
    ]
