# Generated by Django 4.1 on 2022-09-14 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webprojectapp', '0002_alter_apartament_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apartament',
            new_name='Apartment',
        ),
    ]
