# Generated by Django 4.1 on 2022-09-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprojectapp', '0003_rename_apartament_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='estado',
            field=models.CharField(choices=[('available', 'Disponible'), ('unavailable', 'Ocupado')], default=('available', 'Disponible'), max_length=20),
        ),
    ]
