# Generated by Django 4.1 on 2022-09-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprojectapp', '0004_apartment_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='tiene_piscina',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='estado',
            field=models.CharField(choices=[('available', 'Disponible'), ('unavailable', 'Ocupado')], default='available', max_length=20),
        ),
    ]
